/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConfirmModal: typeof import('./src/components/Common/ConfirmModal.vue')['default']
    ImportModal: typeof import('./src/components/Common/ImportModal.vue')['default']
    MainLayout: typeof import('./src/components/Layout/MainLayout.vue')['default']
    MessageBox: typeof import('./src/components/Common/MessageBox.vue')['default']
    PasswordStrengthIndicator: typeof import('./src/components/PasswordStrengthIndicator.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserGroupBasicModal: typeof import('./src/components/Common/UserGroupBasicModal.vue')['default']
    UserGroupModal: typeof import('./src/components/Common/UserGroupModal.vue')['default']
    UserModal: typeof import('./src/components/Common/UserModal.vue')['default']
  }
}
